Update patch set 9
Patch Set 9:

There is a requirement in tripleo-common that clashes with one of our requirements requirements (we don't require oslo.i18n directly). This part of the output from `openstack --help` shows the error:

    [SNIP]

    Commands:
      aggregate add host  Add host to aggregate
      aggregate create  Create a new aggregate
      aggregate delete  Delete an existing aggregate
      aggregate list  List all aggregates
      aggregate remove host  Remove host from aggregate
      aggregate set  Set aggregate properties
      aggregate show  Display aggregate details
      availability zone list  List availability zones and their status
      backup create  Create new backup
      backup delete  Delete backup(s)
      backup list    List backups
      backup restore  Restore backup
      backup show    Display backup details
    Could not load EntryPoint.parse('baremetal_configure_boot = rdomanager_oscplugin.v1.baremetal:ConfigureBootPlugin')
    ERROR: openstack 'ArgumentParser' object has no attribute 'debug'
    Traceback (most recent call last):
      File "/home/dougalmatthews/Code/rdo-management/python-rdomanager-oscplugin/.tox/py34/lib/python3.4/site-packages/cliff/help.py", line 22, in __call__
        factory = ep.load()
      File "/home/dougalmatthews/Code/rdo-management/python-rdomanager-oscplugin/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2344, in load
        self.require(*args, **kwargs)
      File "/home/dougalmatthews/Code/rdo-management/python-rdomanager-oscplugin/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in require
        items = working_set.resolve(reqs, env, installer)
      File "/home/dougalmatthews/Code/rdo-management/python-rdomanager-oscplugin/.tox/py34/lib/python3.4/site-packages/pkg_resources/__init__.py", line 838, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (oslo.i18n 1.6.0 (/home/dougalmatthews/Code/rdo-management/python-rdomanager-oscplugin/.tox/py34/lib/python3.4/site-packages), Requirement.parse('oslo.i18n<1.6.0,>=1.5.0'), {'tripleo-common'})

    [SNIP]

Patch-set: 9