Update patch set 9
Patch Set 9:

Reverted due to error ($ openstack --help): Could not load EntryPoint.parse('baremetal_configure_boot = rdomanager_oscplugin.v1.baremetal:ConfigureBootPlugin')
ERROR: openstack 'ArgumentParser' object has no attribute 'debug'

Patch-set: 9