Update patch set 3
Patch Set 3: Code-Review-1

Bamboo Harvester is right, pep8: ./rdomanager_oscplugin/tests/test_utils.py:22:1: F811 redefinition of unused 'TestCase' from line 19
from unittest import TestCase

Patch-set: 3
Label: Code-Review=-1